export enum EAssistantEngineError {
  INVALID_PARAMS = 'INVALID_PARAMS',
  SERVICE_ERROR = 'SERVICE_ERROR',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  INVALID_ACTING_ACCOUNT = 'INVALID_ACTING_ACCOUNT',
}
