name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NODE_VERSION: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node Version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install RushJS
        run: npm install -g @microsoft/rush
      - name: Install Root Dependencies
        run: npm install
      - name: Install Projects Dependencies
        run: rush update
      - name: Lint Projects
        run: rush lint
      - name: Build Projects
        run: rush rebuild

